// This file is automatically generated. Do not edit it directly.
// Supabase is now ONLY used for Storage (image uploads), NOT for authentication.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate env vars are present (but allow placeholder for template)
if (typeof window !== "undefined" && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === "REPLACE_WITH_SUPABASE_ANON_KEY")) {
  console.warn("⚠️ Supabase env vars not configured. Image uploads will fail.");
  console.warn("   Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env.local");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// 
// NOTE: This client is ONLY for Storage operations (market image uploads).
// Authentication is handled via wallet-based SIWS (Sign-in With Solana).

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false, // Disable auth persistence
    autoRefreshToken: false, // Disable auth token refresh
  }
});

// Alias used by other modules
export { supabase as supabaseClient };
