#!/bin/bash

# Script to apply migration 0007_fix_bets_table_schema.sql to remote Supabase database
# This migration fixes the bets table schema to match what the edge function expects

echo "🔧 Applying migration: 0007_fix_bets_table_schema.sql"
echo "📍 Target: https://ibuzpjefotihoagusrqz.supabase.co"
echo ""
echo "⚠️  IMPORTANT: This migration will:"
echo "   1. DROP the existing bets table (all bet data will be lost)"
echo "   2. CREATE a new bets table with the correct schema"
echo "   3. Add indexes for performance"
echo "   4. Set up RLS policies"
echo "   5. Enable realtime"
echo ""
echo "📋 Steps to apply this migration:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/ibuzpjefotihoagusrqz/sql/new"
echo ""
echo "2. Copy the entire contents of this file:"
echo "   /home/ayo/yesno-anchor/yesno_markets/client/web/supabase/migrations/0007_fix_bets_table_schema.sql"
echo ""
echo "3. Paste into the SQL Editor"
echo ""
echo "4. Click 'Run' to execute the migration"
echo ""
echo "5. Verify the migration succeeded by checking:"
echo "   - Table Editor → bets table should have these columns:"
echo "     • id (uuid)"
echo "     • market_pubkey (text)"
echo "     • bettor_pubkey (text)"
echo "     • username (text)"
echo "     • outcome_index (integer)"
echo "     • outcome_label (text)"
echo "     • amount_sol (numeric)"
echo "     • amount_lamports (bigint)"
echo "     • tx_sig (text)"
echo "     • block_time (timestamptz)"
echo "     • pools_after (jsonb)"
echo "     • probs_after (jsonb)"
echo "     • created_at (timestamptz)"
echo ""
echo "📝 Migration file contents:"
echo "════════════════════════════════════════════════════════════════"
cat /home/ayo/yesno-anchor/yesno_markets/client/web/supabase/migrations/0007_fix_bets_table_schema.sql
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ After applying, test by:"
echo "   1. Place a bet on a market"
echo "   2. Check if the bet appears in the bets table"
echo "   3. Verify probability chart updates"
echo "   4. Verify sparklines update"
echo "   5. Verify recent activity shows the bet"
