[toolchain]
anchor_version = "0.32.1"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-owner.json"

[programs.devnet]
yesno_bets = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.localnet]
yesno_bets = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
